# Generated by Django 4.0.5 on 2023-02-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('filename', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('snippet', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=200)),
                ('snippet', models.CharField(max_length=500)),
                ('pdf_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aiwriter.pdf')),
                ('results', models.ManyToManyField(to='aiwriter.searchresult')),
            ],
        ),
    ]
