# Generated by Django 4.1 on 2023-03-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0003_alter_field_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='ChapterIndex',
        ),
    ]
