# Generated by Django 4.1 on 2023-03-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0004_rename_index_chapterindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterIndex',
            new_name='Index',
        ),
    ]
