# Generated by Django 4.1 on 2023-03-12 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0005_rename_chapterindex_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
