# Generated by Django 4.1 on 2023-03-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0007_company_mymodel_research_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
