# Generated by Django 4.1 on 2023-03-29 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aiwriter', '0009_rename_field_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Document', max_length=100, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='user_uploads/docx/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='user_uploads/pdf/')),
                ('parties', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('liabilitycap', models.CharField(blank=True, max_length=1000, null=True)),
                ('consideration', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('effectivedate', models.DateField(blank=True, max_length=1000, null=True)),
                ('expirydate', models.DateField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('renewal', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
