# Generated by Django 4.1 on 2023-04-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0012_rename_searchresult_googlescholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlescholar',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
