# Generated by Django 4.1 on 2023-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0014_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='researches',
            field=models.ManyToManyField(to='aiwriter.research'),
        ),
    ]
