# Generated by Django 4.1 on 2023-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0015_file_researches'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
