# Generated by Django 4.1 on 2023-04-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0016_file_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleScholarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('snippet', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Document', max_length=100, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='user_uploads/docx/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='user_uploads/pdf/')),
                ('parties', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('liabilitycap', models.CharField(blank=True, max_length=1000, null=True)),
                ('consideration', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('effectivedate', models.DateField(blank=True, max_length=1000, null=True)),
                ('expirydate', models.DateField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('renewal', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='googlescholar',
            name='research',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='GoogleScholar',
        ),
        migrations.AddField(
            model_name='research',
            name='googlefile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aiwriter.googlescholarfile'),
        ),
        migrations.AddField(
            model_name='research',
            name='uploadedfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aiwriter.uploadedfile'),
        ),
    ]
